spring:   
  thymeleaf:
    cache: false
    encoding: UTF-8
  mvc:
    favicon:
      enabled: false
      
      
server:
  servlet:
    context-path: /
  port: 80
  
logging:
  level:
    root: info
    com.example.demo: debug

#以下是模拟数据配置(注意：编辑数据时要遵循yml配置文件规范)
demodata: 
  index01: 
    chart1:  
      xcol: 黄陂,汉南,东西湖,新洲,江夏,中心城区  
      yval: 23.2, 25.6, 76.7, 135.6, 162.2, 43.3  
    chart2: 
      xcol: 汉口,汉阳,沌口,武昌,东湖高新,蔡甸  
      yval: 23.2, 25.6, 76.7, 135.6, 125.5, 20.3
    chart3:
      year15: 4, 6, 8, 11, 12, 11.5, 11, 11, 11.1, 11.2, 13, 15  
      year16: 10.6, 12, 15, 14.8, 13.2, 12, 10.2, 10, 12, 16, 22, 23  
      year17: 7, 10, 15, 20, 22, 21.5, 20, 18, 18.5, 19, 21, 20
    region:
      huangpi: 黄陂情况描述
      xinzhou: 新洲情况描述
      dongxihu: 东西湖情况描述
      shiqu: 自行填写市区情况描述市区情况描述市区情况描述市区情况描述市区情况描述市区情况描述市区情况描述
      caidian: 蔡甸 情况描述
      hannan: 汉南情况描述
      jiangxia: 江夏 情况描述
    rect: 
      rect1: 456,2401,4562
      rect2: 1456,2456,4563
      rect3: 1542,2841,2535
  index02: 
    chart1: 
      ycol: 武昌,汉口,东湖高新,沌口,汉阳
      year16: 120, 132, 101, 134, 90
      year17: 320, 302, 301, 334, 390
      year18: 820, 832, 901, 934, 1290
    chart2: 
      xcol: 武昌,汉口,东湖高新,沌口,汉阳  
      yval: 31,34,17,10,9
      colorList: C1232B,0099cc,FCCE10,0099cc,27727B,0099cc,9BCA63,0099cc,F3A43B,0099cc,D7504B,0099cc,F4E001,F0805A,26C0C0
    chart3: 
      xcol: 2011年,2012年,2013年,2014年,2015年,2016年,2017年
      ywhole: 7, 7.9, 8, 11, 12, 13.8, 15
      yassist: 1, 3, 4, 4, 4.3, 5.5, 6
    region:
      hankou: 自行填写汉口情况描述汉口情况描述汉口情况描述汉口情况描述
      hanyang: 自行填写汉阳情况描述汉阳情况描述汉阳情况描述汉阳情况描述
      zhuankou: 自行填写沌口情况描述沌口情况描述沌口情况描述沌口情况描述
      wuchang: 自行填写武昌情况描述武昌情况描述武昌情况描述武昌情况描述
      dongxin: 自行填写东新情况描述东新情况描述东新情况描述东新情况描述
    r1Data:
      - 0.519,省委
      - 0.983,长江隧道
      - 0.123,武汉电视台
      - 0.519,市政府
      - 0.983,武汉铁路局
      - 0.123,龟山电视台
      - 0.519,华中国电
      - 0.983,省公司
      - 0.123,网公司
      - 0.983,省公司
      - 0.983,省公司
      - 0.983,省公司
      - 0.519,省委
      - 0.983,长江隧道
      - 0.123,武汉电视台
      - 0.519,市政府
      - 0.983,武汉铁路局
      - 0.123,龟山电视台
      - 0.519,华中国电
      - 0.519,省委
      - 0.983,长江隧道
      - 0.123,武汉电视台
      - 0.519,市政府
      - 0.983,武汉铁路局
      - 0.123,龟山电视台
      - 0.519,华中国电
      - 0.983,省公司
      - 0.123,网公司
      - 0.983,省公司
      - 0.983,省公司
      - 0.983,省公司
      - 0.519,省委
      - 0.983,长江隧道
      - 0.123,武汉电视台
      - 0.519,市政府
      - 0.983,武汉铁路局
      - 0.123,龟山电视台
      - 0.519,华中国电
    r2Data: 
      - 20180604,变电运维室,汉509新路器,汉509开关小车返厂,10KW常区线,在修
      - 20180605,变电运维室,汉508新路器,汉508开关小车返厂,8KW常区线,正常
      - 20180604,变电运维室,汉507新路器,汉507开关小车返厂,7KW常区线,在修
      - 20180605,变电运维室,汉506新路器,汉506开关小车返厂,33KW常区线,正常
      - 20180604,变电运维室,汉505新路器,汉505开关小车返厂,10KW常区线,在修
      - 20180605,变电运维室,汉504新路器,汉504开关小车返厂,100KW常区线,正常
   
         